/** Sample diagrams and a sample conversation for the dev playground and the tests. */
import type { Conversation, GraphEntry, GraphSpec } from '@codesplainer/shared';

export const architectureSpec: GraphSpec = {
  title: 'How Codesplainer answers a question',
  summary:
    'The web UI sends the question to the local server, which runs a coding agent over your code.',
  kind: 'architecture',
  nodes: [
    { id: 'user', label: 'You', kind: 'actor', refs: [], expandable: false },
    {
      id: 'web',
      label: 'Web UI',
      kind: 'ui',
      detail: 'React app: canvas, map, code viewer',
      group: 'frontend',
      refs: [{ folder: 'web', path: 'src/App.tsx', startLine: 1 }],
      expandable: true,
    },
    {
      id: 'canvas',
      label: 'Graph canvas',
      kind: 'component',
      detail: 'Draws diagrams with React Flow + ELK',
      group: 'frontend',
      refs: [{ folder: 'web', path: 'src/graph/GraphCanvas.tsx', startLine: 12 }],
      expandable: true,
    },
    {
      id: 'api',
      label: 'API server',
      kind: 'service',
      detail: 'Routes, SSE stream, job queue',
      group: 'backend',
      refs: [
        { folder: 'server', path: 'src/index.ts', startLine: 18 },
        { folder: 'server', path: 'src/routes.ts', startLine: 4 },
      ],
      expandable: true,
      highlight: true,
    },
    {
      id: 'runner',
      label: 'Agent runner',
      kind: 'service',
      detail: 'Builds the prompt and parses the answer',
      group: 'backend',
      refs: [{ folder: 'server', path: 'src/agents/runner.ts', startLine: 42 }],
      expandable: true,
      highlight: true,
    },
    {
      id: 'store',
      label: 'Conversation store',
      kind: 'store',
      detail: 'JSON files per conversation',
      group: 'backend',
      refs: [{ folder: 'server', path: 'src/store.ts', startLine: 9 }],
      expandable: true,
    },
    {
      id: 'agent',
      label: 'Coding agent CLI',
      kind: 'external',
      detail: 'Kiro, Claude Code, Codex or ACP',
      refs: [],
      expandable: false,
    },
    {
      id: 'code',
      label: 'Your repository',
      kind: 'module',
      refs: [{ folder: 'web', path: '', isDir: true }],
      expandable: true,
    },
  ],
  edges: [
    { id: 'e1', from: 'user', to: 'web', kind: 'call', label: 'asks' },
    { id: 'e2', from: 'web', to: 'api', kind: 'call', label: 'POST /api/ask' },
    { id: 'e3', from: 'api', to: 'runner', kind: 'call', label: 'queue job' },
    { id: 'e4', from: 'runner', to: 'agent', kind: 'call', label: 'spawns' },
    { id: 'e5', from: 'agent', to: 'code', kind: 'read', label: 'reads' },
    { id: 'e6', from: 'runner', to: 'store', kind: 'write', label: 'saves diagram' },
    { id: 'e7', from: 'api', to: 'web', kind: 'event', label: 'SSE updates' },
    { id: 'e8', from: 'web', to: 'canvas', kind: 'contains' },
  ],
  groups: [
    { id: 'frontend', label: 'Browser' },
    { id: 'backend', label: 'Local server' },
  ],
  suggestions: ['How is the prompt built?', 'Where are diagrams stored?'],
};

export const flowSpec: GraphSpec = {
  title: 'What happens on “Explain & expand”',
  summary: 'The clicked box becomes the question of a new, deeper diagram.',
  kind: 'flow',
  nodes: [
    { id: 'click', label: 'Double-click a box', kind: 'actor', refs: [], expandable: false },
    {
      id: 'prompt',
      label: 'Build expand prompt',
      kind: 'step',
      detail: 'Parent diagram + box + refs',
      refs: [{ folder: 'server', path: 'src/agents/prompt.ts', startLine: 88 }],
      expandable: true,
    },
    {
      id: 'run',
      label: 'Run agent',
      kind: 'step',
      detail: 'Streams activity to the UI',
      refs: [],
      expandable: true,
    },
    {
      id: 'valid',
      label: 'Valid diagram JSON?',
      kind: 'decision',
      refs: [],
      expandable: false,
      highlight: true,
    },
    {
      id: 'normalize',
      label: 'normalizeGraphSpec()',
      kind: 'function',
      detail: 'Fixes kinds, drops dangling edges',
      refs: [{ folder: 'shared', path: 'src/graph.ts', startLine: 312 }],
      expandable: true,
    },
    { id: 'retry', label: 'Ask agent to fix', kind: 'step', refs: [], expandable: false },
    { id: 'save', label: 'Save entry', kind: 'store', refs: [], expandable: true },
    { id: 'render', label: 'Render child diagram', kind: 'ui', refs: [], expandable: true },
  ],
  edges: [
    { id: 'f1', from: 'click', to: 'prompt', kind: 'flow', step: 1 },
    { id: 'f2', from: 'prompt', to: 'run', kind: 'flow', step: 2 },
    { id: 'f3', from: 'run', to: 'valid', kind: 'flow', step: 3 },
    {
      id: 'f4',
      from: 'valid',
      to: 'normalize',
      kind: 'flow',
      label: 'yes',
      step: 4,
      refs: [{ folder: 'server', path: 'src/jobs/generation.ts', startLine: 591, endLine: 591 }],
    },
    { id: 'f5', from: 'valid', to: 'retry', kind: 'flow', label: 'no' },
    { id: 'f6', from: 'retry', to: 'run', kind: 'flow', label: 'once' },
    {
      id: 'f7',
      from: 'normalize',
      to: 'save',
      kind: 'write',
      step: 5,
      refs: [{ folder: 'server', path: 'src/jobs/generation.ts', startLine: 604, endLine: 604 }],
    },
    { id: 'f8', from: 'save', to: 'render', kind: 'event', label: 'graph.done', step: 6 },
  ],
  groups: [],
  suggestions: [],
};

export const sequenceSpec: GraphSpec = {
  title: 'Asking a question, step by step',
  kind: 'sequence',
  nodes: [
    { id: 'user', label: 'You', kind: 'actor', refs: [], expandable: false },
    { id: 'ui', label: 'Web UI', kind: 'ui', refs: [], expandable: true },
    {
      id: 'api',
      label: 'API server',
      kind: 'service',
      refs: [{ folder: 'server', path: 'src/routes.ts', startLine: 40 }],
      expandable: true,
      highlight: true,
    },
    { id: 'agent', label: 'Agent', kind: 'external', refs: [], expandable: false },
    { id: 'store', label: 'Store', kind: 'store', refs: [], expandable: true },
  ],
  edges: [
    { id: 's1', from: 'user', to: 'ui', kind: 'call', label: 'types a question', step: 1 },
    {
      id: 's2',
      from: 'ui',
      to: 'api',
      kind: 'call',
      label: 'POST /api/ask',
      step: 2,
      refs: [{ folder: 'web', path: 'src/lib/api.ts', startLine: 64, endLine: 64, symbol: 'ask' }],
    },
    { id: 's3', from: 'api', to: 'store', kind: 'write', label: 'queued entry', step: 3 },
    {
      id: 's4',
      from: 'api',
      to: 'agent',
      kind: 'call',
      label: 'spawn with prompt',
      step: 4,
      refs: [
        {
          folder: 'server',
          path: 'src/jobs/generation.ts',
          startLine: 575,
          endLine: 575,
          symbol: 'run',
        },
      ],
    },
    { id: 's5', from: 'agent', to: 'agent', kind: 'call', label: 'explores the code', step: 5 },
    { id: 's6', from: 'agent', to: 'api', kind: 'data', label: 'diagram JSON', step: 6 },
    { id: 's7', from: 'api', to: 'api', kind: 'call', label: 'normalize', step: 7 },
    { id: 's8', from: 'api', to: 'store', kind: 'write', label: 'save', step: 8 },
    { id: 's9', from: 'api', to: 'ui', kind: 'event', label: 'SSE graph.done', step: 9 },
    { id: 's10', from: 'ui', to: 'user', kind: 'data', label: 'shows diagram', step: 10 },
  ],
  groups: [],
  suggestions: [],
};

const pkg = (
  id: string,
  label: string,
  detail?: string,
  group?: string,
): GraphSpec['nodes'][number] => ({
  id,
  label,
  kind: 'module',
  refs: [{ folder: 'repo', path: `packages/${id}`, isDir: true }],
  expandable: true,
  ...(detail ? { detail } : {}),
  ...(group ? { group } : {}),
});

export const bigSpec: GraphSpec = {
  title: 'Monorepo dependency map',
  kind: 'dependency',
  nodes: [
    pkg('app', 'app', 'Next.js shell', 'apps'),
    pkg('admin', 'admin', 'Back office', 'apps'),
    pkg('cli', 'cli', 'Command line tool', 'apps'),
    pkg('ui-kit', 'ui-kit', 'Design system'),
    pkg('forms', 'forms'),
    pkg('charts', 'charts', 'D3 wrappers'),
    pkg('api-client', 'api-client', 'Typed fetch client'),
    pkg('auth', 'auth', 'Sessions & tokens'),
    pkg('billing', 'billing', 'Stripe integration'),
    pkg('search', 'search'),
    pkg('i18n', 'i18n', 'Translations'),
    pkg('analytics', 'analytics'),
    pkg('core', 'core', 'Domain model', 'foundation'),
    pkg('utils', 'utils', 'Shared helpers', 'foundation'),
    pkg('config', 'config', 'Env & feature flags', 'foundation'),
    pkg('logger', 'logger', undefined, 'foundation'),
    { id: 'db', label: 'Postgres', kind: 'store', refs: [], expandable: false },
    { id: 'stripe', label: 'Stripe', kind: 'external', refs: [], expandable: false },
    { id: 'es', label: 'Elasticsearch', kind: 'external', refs: [], expandable: false },
    { id: 'events', label: 'Event bus', kind: 'queue', refs: [], expandable: true },
  ],
  edges: [
    ['app', 'ui-kit'],
    ['app', 'forms'],
    ['app', 'api-client'],
    ['app', 'auth'],
    ['app', 'i18n'],
    ['app', 'analytics'],
    ['admin', 'ui-kit'],
    ['admin', 'charts'],
    ['admin', 'api-client'],
    ['admin', 'billing'],
    ['cli', 'api-client'],
    ['cli', 'config'],
    ['forms', 'ui-kit'],
    ['charts', 'ui-kit'],
    ['api-client', 'core'],
    ['auth', 'core'],
    ['auth', 'db'],
    ['billing', 'stripe'],
    ['billing', 'core'],
    ['billing', 'events'],
    ['search', 'es'],
    ['search', 'core'],
    ['app', 'search'],
    ['analytics', 'events'],
    ['core', 'utils'],
    ['core', 'logger'],
    ['config', 'utils'],
    ['logger', 'config'],
    ['i18n', 'utils'],
  ].map(([from, to], i) => ({
    id: `d${i + 1}`,
    from: from as string,
    to: to as string,
    kind: 'dependency' as const,
  })),
  groups: [
    { id: 'apps', label: 'Apps' },
    { id: 'foundation', label: 'Foundation' },
  ],
  suggestions: [],
};

export const stateSpec: GraphSpec = {
  title: 'Lifecycle of a diagram',
  kind: 'state',
  nodes: [
    { id: 'queued', label: 'Queued', kind: 'step', refs: [], expandable: false },
    {
      id: 'running',
      label: 'Running',
      kind: 'step',
      detail: 'Agent is exploring',
      refs: [],
      expandable: false,
    },
    { id: 'done', label: 'Done', kind: 'step', refs: [], expandable: false, highlight: true },
    { id: 'error', label: 'Failed', kind: 'event', refs: [], expandable: false },
    { id: 'cancelled', label: 'Cancelled', kind: 'event', refs: [], expandable: false },
  ],
  edges: [
    { id: 't1', from: 'queued', to: 'running', kind: 'flow', label: 'slot free' },
    { id: 't2', from: 'running', to: 'done', kind: 'flow', label: 'valid JSON' },
    { id: 't3', from: 'running', to: 'error', kind: 'flow', label: 'crash / timeout' },
    { id: 't4', from: 'running', to: 'cancelled', kind: 'flow', label: 'user cancels' },
    { id: 't5', from: 'error', to: 'queued', kind: 'flow', label: 'retry' },
    { id: 't6', from: 'running', to: 'running', kind: 'event', label: 'activity' },
  ],
  groups: [],
  suggestions: [],
};

const storeSpec: GraphSpec = {
  title: 'Conversation store internals',
  kind: 'structure',
  nodes: [
    {
      id: 'store',
      label: 'ConversationStore',
      kind: 'class',
      refs: [{ path: 'src/store.ts', startLine: 9 }],
      expandable: true,
      highlight: true,
    },
    {
      id: 'index',
      label: 'index.json',
      kind: 'file',
      detail: 'Summaries for the sidebar',
      refs: [],
      expandable: false,
    },
    {
      id: 'conv',
      label: '<id>.json',
      kind: 'file',
      detail: 'One file per conversation',
      refs: [],
      expandable: false,
    },
    { id: 'lock', label: 'Write lock', kind: 'function', refs: [], expandable: true },
    { id: 'schema', label: 'conversationSchema', kind: 'data', refs: [], expandable: true },
  ],
  edges: [
    { id: 'c1', from: 'store', to: 'index', kind: 'write' },
    { id: 'c2', from: 'store', to: 'conv', kind: 'write' },
    { id: 'c3', from: 'store', to: 'lock', kind: 'call', label: 'serializes' },
    { id: 'c4', from: 'store', to: 'schema', kind: 'dependency', label: 'validates' },
  ],
  groups: [],
  suggestions: [],
};

const runnerSpec: GraphSpec = {
  title: 'Inside the agent runner',
  kind: 'flow',
  nodes: [
    { id: 'job', label: 'Job', kind: 'data', refs: [], expandable: false },
    {
      id: 'prompt',
      label: 'buildPrompt()',
      kind: 'function',
      refs: [{ path: 'src/agents/prompt.ts', startLine: 20 }],
      expandable: true,
      highlight: true,
    },
    { id: 'spawn', label: 'Spawn CLI', kind: 'step', refs: [], expandable: true },
    { id: 'parse', label: 'Parse output', kind: 'step', refs: [], expandable: true },
    { id: 'emit', label: 'Emit events', kind: 'event', refs: [], expandable: false },
  ],
  edges: [
    { id: 'r1', from: 'job', to: 'prompt', kind: 'flow', step: 1 },
    { id: 'r2', from: 'prompt', to: 'spawn', kind: 'flow', step: 2 },
    { id: 'r3', from: 'spawn', to: 'parse', kind: 'flow', step: 3 },
    { id: 'r4', from: 'parse', to: 'emit', kind: 'event', step: 4 },
  ],
  groups: [],
  suggestions: [],
};

function entry(
  id: string,
  origin: GraphEntry['origin'],
  extra: Partial<GraphEntry> = {},
): GraphEntry {
  return {
    id,
    origin,
    question: `Question ${id}`,
    status: 'done',
    provider: 'mock',
    detail: 'balanced',
    warnings: [],
    createdAt: '2026-01-01T10:00:00.000Z',
    activity: [],
    attempt: 1,
    ...extra,
  };
}

export const sampleConversation: Conversation = {
  id: 'c-demo',
  title: 'Onboarding tour',
  workspaceId: 'w1',
  createdAt: '2026-01-01T10:00:00.000Z',
  updatedAt: '2026-01-01T10:30:00.000Z',
  graphs: [
    entry(
      'g1',
      { type: 'question' },
      { question: 'How does Codesplainer answer a question?', spec: architectureSpec },
    ),
    entry(
      'g2',
      { type: 'expand', parentGraphId: 'g1', nodeId: 'runner', nodeLabel: 'Agent runner' },
      { question: 'Expand: Agent runner', spec: runnerSpec },
    ),
    entry(
      'g3',
      { type: 'expand', parentGraphId: 'g1', nodeId: 'store', nodeLabel: 'Conversation store' },
      { question: 'Expand: Conversation store', spec: storeSpec },
    ),
    entry(
      'g4',
      { type: 'ask-node', parentGraphId: 'g1', nodeId: 'api', nodeLabel: 'API server' },
      {
        question: 'What happens between the API server and the agent, step by step?',
        spec: sequenceSpec,
      },
    ),
    entry(
      'g5',
      { type: 'expand', parentGraphId: 'g2', nodeId: 'prompt', nodeLabel: 'buildPrompt()' },
      { question: 'Expand: buildPrompt()', spec: flowSpec },
    ),
    entry(
      'g6',
      { type: 'ask-graph', parentGraphId: 'g2' },
      { question: 'Which states can a diagram be in?', spec: stateSpec },
    ),
    entry(
      'g7',
      { type: 'expand', parentGraphId: 'g3', nodeId: 'lock', nodeLabel: 'Write lock' },
      { question: 'Expand: Write lock', status: 'running', spec: undefined },
    ),
    entry(
      'g8',
      {
        type: 'ask-code',
        ref: { folder: 'server', path: 'src/agents/runner.ts', startLine: 42 },
        parentGraphId: 'g2',
        nodeId: 'parse',
      },
      {
        question: 'Why is the output parsed twice?',
        status: 'error',
        error: 'Agent exited with code 1: rate limited',
        spec: undefined,
      },
    ),
    entry(
      'g9',
      { type: 'question' },
      { question: 'Show me the package dependencies', spec: bigSpec },
    ),
    entry(
      'g10',
      { type: 'ask-graph', parentGraphId: 'g9' },
      { question: 'Which packages use the event bus?', status: 'queued' },
    ),
  ],
};
